### ISSUE TITLE
'types/event.h' file not found

### ISSUE THREAD

**Issue by pquerner** [orbisdev/liborbis#1]
liborbis/liborbis2d$ make
clang  -c source/orbis2d.c -std=c11 -O3 -Wall -m64 -mcmodel=large -Wno-zero-length-array -Wno-format-pedantic -I. -Iinclude  -ffreestanding -nostdlib -nostdinc -fno-builtin -fno-stack-protector -D__PS4__ -I/home/vagrant/ps4sdk/include -I /home/vagrant/ps4sdk/include/sce -target x86_64-scei-ps4  -fPIC -o build/orbis2d.c.o
source/orbis2d.c:10:10: fatal error: 'types/event.h' file not found
#include <types/event.h>
         ^
1 error generated.
make: *** [build/orbis2d.c.o] Error 1

**Comment by psxdev** [comment]
Fixed in ps4sdk, check last commit
